DROP TABLE IF EXISTS INCLUYE;
DROP TABLE IF EXISTS MODELO;
DROP TABLE IF EXISTS EQUIPAMIENTO;
DROP TABLE IF EXISTS MOTOR;

DROP SEQUENCE IF EXISTS SEQ_INCLUYE;
DROP SEQUENCE IF EXISTS SEQ_MODELO;
DROP SEQUENCE IF EXISTS SEQ_EQUIPAMIENTO;
DROP SEQUENCE IF EXISTS SEQ_MOTOR;

CREATE SEQUENCE SEQ_MOTOR START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MODELO START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EQUIPAMIENTO START WITH 100 INCREMENT BY 1;

CREATE TABLE MOTOR (
    ID BIGINT,
    Tipo VARCHAR2(15),
    Potencia FLOAT,
    Precio FLOAT,
    CONSTRAINT PK_MOTOR PRIMARY KEY (ID),
    CONSTRAINT CK1_MOTOR CHECK (Precio > 0),
    CONSTRAINT CK2_MOTOR CHECK (Potencia > 0)
);
CREATE TABLE MODELO (
    ID BIGINT,
    Nombre VARCHAR2(15),
    Precio_base FLOAT,
    IDMOT BIGINT,
    CONSTRAINT PK_MODELO PRIMARY KEY (ID),
    CONSTRAINT FK_MODELO_MOTOR FOREIGN KEY (ID) REFERENCES MOTOR(ID),
    CONSTRAINT CK1_MODELO CHECK (Precio_base > 0)
);
CREATE TABLE EQUIPAMIENTO (
    ID BIGINT,
    Nombre VARCHAR2(15),
    Precio FLOAT,
    CONSTRAINT PK_EQUIPAMIENTO PRIMARY KEY (ID),
    CONSTRAINT CK1_EQUIPAMIENTO CHECK (Precio > 0)
);
CREATE TABLE INCLUYE (
    IDMOD BIGINT,
    IDE BIGINT,
    Descuento FLOAT,
    CONSTRAINT PK_INCLUYE PRIMARY KEY (IDMOD, IDE),
    CONSTRAINT FK1_INCLUYE FOREIGN KEY (IDMOD) REFERENCES MODELO(ID),
    CONSTRAINT FK2_INCLUYE FOREIGN KEY (IDE) REFERENCES MOTOR(ID)
);